Downgrade express to avoid error about express modules that are no longer bundled with express:
```
Error: Most middleware (like logger) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/Users/rosetoomey/workspace/insight-api/node_modules/express/lib/express.js:89:13)
    at module.exports (/Users/rosetoomey/workspace/insight-api/config/express.js:31:19)
    at Object.<anonymous> (/Users/rosetoomey/workspace/insight-api/insight.js:155:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```